/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "zdursutmswstzfqdziwz"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkdXJzdXRtc3dzdHpmcWR6aXd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIyNzY4MzgsImV4cCI6MjA4Nzg1MjgzOH0.D5-5Vv4XsN269CzO-vs_mRM4TNOxp2ZP0lmhgkL6E_E"